/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_workercontext_free: (a: number, b: number) => void;
export const workercontext_init: (a: number, b: number) => number;
export const workercontext_process_draw_command: (a: number, b: number, c: number) => void;
export const setup_worker: (a: number, b: number) => void;
export const __wbg_drawengine_free: (a: number, b: number) => void;
export const drawengine_new: (a: number, b: number, c: number) => void;
export const drawengine_resize: (a: number, b: number, c: number) => void;
export const drawengine_begin_stroke: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => void;
export const drawengine_add_point: (a: number, b: number, c: number, d: number, e: number) => void;
export const drawengine_end_stroke: (a: number, b: number) => void;
export const drawengine_remove_stroke: (a: number, b: number) => number;
export const drawengine_clear: (a: number, b: number) => void;
export const drawengine_undo: (a: number, b: number) => void;
export const drawengine_redo: (a: number, b: number) => void;
export const drawengine_get_shared_buffer: (a: number) => number;
export const drawengine_render: (a: number, b: number) => void;
export const __wbg_webgpurenderer_free: (a: number, b: number) => void;
export const webgpurenderer_new: (a: number) => number;
export const webgpurenderer_render: (a: number, b: number) => void;
export const webgpurenderer_resize: (a: number, b: number, c: number) => void;
export const __wbg_sharedbuffer_free: (a: number, b: number) => void;
export const sharedbuffer_new: (a: number, b: number) => void;
export const sharedbuffer_buffer: (a: number) => number;
export const sharedbuffer_write_pixels: (a: number, b: number, c: number, d: number, e: number) => void;
export const __wbg_drawingcontext_free: (a: number, b: number) => void;
export const drawingcontext_new: (a: number, b: number) => number;
export const drawingcontext_draw_stroke: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const drawingcontext_clear: (a: number, b: number, c: number, d: number) => void;
export const drawingcontext_get_pixels: (a: number, b: number) => void;
export const drawingcontext_set_shared_buffer: (a: number, b: number) => void;
export const drawingcontext_copy_to_shared_buffer: (a: number, b: number) => void;
export const drawingcontext_draw_stroke_from_typed_array: (a: number, b: number, c: number, d: number, e: number) => void;
export const drawingcontext_resize: (a: number, b: number, c: number, d: number) => void;
export const main: () => void;
export const check_webgpu_support: () => number;
export const __wbindgen_export_0: (a: number) => void;
export const __wbindgen_export_1: (a: number, b: number, c: number) => void;
export const __wbindgen_export_2: (a: number, b: number) => number;
export const __wbindgen_export_3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export_5: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_start: () => void;
